### PR TITLE
Add python data loading script for neuropixels 1.0e headstage workflow

### LINKED ISSUE #88: Add python load scripts to examples in the Hardware Guide
Missing on:
- headstage64 
- NP1.0e
- NP2.0e

### PR DESCRIPTION
**Pull request by jonnew**
- Modified example workflow a bit to facilitate this. Namely, timestamps in files names were replaced with file counts because the headstage's design means that data streams start at signficantly different times
- Fixes #88

### CODE REVIEW

**Review by cjsha — APPROVED** [review]
> timestamps in files names were replaced with file counts because the headstage's design means that data streams start at signficantly different times

That's fine. ContextTask is timestamped after configuring the headstage. That should be sufficient for recording a software timestamp of when acquisition started. Do you think this is a standard we should try maintaining through the docs?

I didn't have data to recreate these plots. I trust it looks fine so I'll approve, but I can also acquire some or find your data to look at the plots myself if you want me to do that before merging.

**Comment by jonnew** [comment]
Actually kinda do, but I dont care enough to make a big deal out of it.

Timestamps are the best for filenames. But they become extremely annoying if there are bunch of files for a single session that get created at different times and therefore have different suffixes. This is going to be common with this library, so we should stay away from them.

It also indicates we need a more unified recording operator, but this is already on the TODO.

**Comment by jonnew** [comment]
Note that this script still needs to be inserted into the docs for this merge to be complete.

**Review by cjsha — APPROVED** [review]
I integrated the np1hs loading script identically as the breakout loading script

**Pull request merged**
