### PR TITLE
Add badges for configuration/acquisition properties

### LINKED ISSUE #30: Categorize properties into "Configuration Property" or "Acquisition Property" categories.
Resolving this issue is contingent on resolving issue #29.

### PR DESCRIPTION
**Pull request by cjsha**
This does not have an effect until #108 is merged
Resolves #30

### CODE REVIEW

**Comment by bparks13** [comment]
Is the only place that we define the categories in the Getting Started page? It might be confusing for someone to use F1 help and see these tags but not fully understand what they mean.

Is it possible to hyperlink these tags to go to the [Property Categories](https://open-ephys.github.io/bonsai-onix1-docs/articles/getting-started/property-categories.html) page?

**Comment by bparks13** [comment]
Tool tip might work, as long as we can have a single source of truth that the webpage and the tooltip are both pulling from so they don't get desynchronized

**Comment by cjsha** [comment]
couldn't get the tooltip going. instead I made an issue #130 and put in the wishlist category

**Review by bparks13 — APPROVED** [review]
Looks good to me, tested this by merging with main locally to see the badges pop up, and the hyperlinks worked for me.

**Pull request merged**
